export enum appTypes {
    TRIGGER_QUERY_GIFY = "TRIGGER_QUERY_GIFY",
    QUERY_GIFY = "QUERY_GIFY",
    QUERY_TRENDING_GIFY = "QUERY_TRENDING_GIFY",
    TRIGGER_TRENDING_GIFY = "TRIGGER_TRENDING_GIFY",
}